=== makno/minicraft/minicraft/xml/karte.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Elemente -->
<!ELEMENT karte (spieler,ressourcen,reihe*)>

<!ELEMENT spieler (name,id,zeitstempel)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT zeitstempel (#PCDATA)>

<!ELEMENT ressourcen (ressource*)>
<!ELEMENT ressource (#PCDATA)>

<!ELEMENT reihe (feld*)>
<!ELEMENT feld (#PCDATA)>

<!ATTLIST ressource id CDATA #REQUIRED>

=== makno/minicraft/minicraft/maps/map_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE karte SYSTEM "xml/karte.dtd">
<karte>
  <spieler>
    <name>1</name>
    <id>$5$saltycrackers!!!$G96bES5QKtnhvFAy3pZFHstKMo312JsT.uSn/PoDUG.</id>
    <zeitstempel>1465756822</zeitstempel>
  </spieler>
  <ressourcen><ressource id="1">12</ressource><ressource id="2">0</ressource><ressource id="3">29</ressource><ressource id="7">2001</ressource></ressourcen>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>1</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>9</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>3</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>3</feld>
  </reihe>
  <reihe>
    <feld>3</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>4</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>4</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>7</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>5</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>5</feld>
    <feld>2</feld>
    <feld>5</feld>
  </reihe>
</karte>

=== makno/minicraft/minicraft/maps/map_test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE karte SYSTEM "xml/karte.dtd">
<karte>
  <spieler>
    <name>test</name>
    <id>$5$saltycrackers!!!$govbWAR6.WD6rQJbD6ud6.jBGoWly/4TRkUGVp7o835</id>
    <zeitstempel>1465804464</zeitstempel>
  </spieler>
  <ressourcen><ressource id="1">50</ressource><ressource id="2">50</ressource><ressource id="3">50</ressource><ressource id="7">2002</ressource></ressourcen>
  <reihe>
    <feld>1</feld>
    <feld>2</feld>
    <feld>3</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>3</feld>
    <feld>2</feld>
    <feld>3</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>4</feld>
    <feld>4</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>4</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>5</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>5</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>5</feld>
    <feld>2</feld>
  </reihe>
</karte>

=== makno/minicraft/minicraft/maps/map_mathias.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE karte SYSTEM "xml/karte.dtd">
<karte>
  <spieler>
    <name>mathias</name>
    <id>$5$saltycrackers!!!$N7UAsehtE7VC1TTTrVp/VyEZni0D.BQmCkhZ.WijS3D</id>
    <zeitstempel>1465806667</zeitstempel>
  </spieler>
  <ressourcen><ressource id="1">286</ressource><ressource id="2">140</ressource><ressource id="3">11</ressource><ressource id="7">125</ressource><ressource id="4">27</ressource><ressource id="5">25</ressource><ressource id="6">22</ressource></ressourcen>
  <reihe>
    <feld>1</feld>
    <feld>11</feld>
    <feld>6</feld>
    <feld>6</feld>
    <feld>6</feld>
    <feld>3</feld>
    <feld>3</feld>
  </reihe>
  <reihe>
    <feld>12</feld>
    <feld>6</feld>
    <feld>6</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
  </reihe>
  <reihe>
    <feld>9</feld>
    <feld>7</feld>
    <feld>7</feld>
    <feld>7</feld>
    <feld>7</feld>
    <feld>7</feld>
    <feld>7</feld>
  </reihe>
  <reihe>
    <feld>7</feld>
    <feld>7</feld>
    <feld>8</feld>
    <feld>8</feld>
    <feld>7</feld>
    <feld>7</feld>
    <feld>10</feld>
  </reihe>
  <reihe>
    <feld>6</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>6</feld>
  </reihe>
  <reihe>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
  </reihe>
  <reihe>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
    <feld>3</feld>
  </reihe>
</karte>

=== makno/minicraft/minicrafty/maps/map_user.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE karte SYSTEM "xml/karte.dtd">
<karte>
  <spieler>
    <name>user</name>
    <id>$5$saltycrackers!!!$3tll3erlIiRcXCq3UIx8HDvnjKaQEoPZvKwoG9LxB35</id>
    <zeitstempel>1465916952</zeitstempel>
  </spieler>
  <ressourcen><ressource id="1">1</ressource><ressource id="2">1</ressource><ressource id="3">1</ressource><ressource id="7">1</ressource></ressourcen>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>1</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>3</feld>
    <feld>3</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>3</feld>
    <feld>2</feld>
    <feld>4</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>4</feld>
    <feld>2</feld>
    <feld>4</feld>
    <feld>2</feld>
    <feld>5</feld>
    <feld>5</feld>
  </reihe>
  <reihe>
    <feld>2</feld>
    <feld>2</feld>
    <feld>5</feld>
    <feld>2</feld>
    <feld>5</feld>
    <feld>2</feld>
    <feld>2</feld>
  </reihe>
  <reihe>
    <feld>5</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>2</feld>
    <feld>5</feld>
    <feld>5</feld>
  </reihe>
</karte>
